name: CI
on:
  pull_request:
    branches: 
      - 'integration'
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"
          cache: 'maven'
        
      - name: Test with Maven
        run: mvn clean test

  package:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: "17"
            distribution: "corretto"
            cache: 'maven'

        - name: Test with Maven
          run: mvn clean package

        - name: Archive package result
          uses: actions/upload-artifact@v3
          with:
            name: package
            path: target/Universe-Exploration-1.0-SNAPSHOT.jar

  sonarQube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"
          cache: 'maven'

      - name: SonarQube
        run: mvn sonar:sonar -Dsonar.host.url=${{ secrets.SONARQUBE_URL }} -Dsonar.projectKey=Universe-Exploration -Dsonar.projectName=Universe-Exploration -Dsonar.token=${{ secrets.SONARQUBE_TOKEN }}